version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: bistrodb
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: bistromenu
    volumes:
      - ./DBScripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: bistro_backend
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bistromenu
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: bistro_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"